name: Documentation task
description: Créer ou modifier une documentation
title: "[Documentation] "
labels:
  - area:docs
  - type:docs
  - status:ready
body:
  - type: textarea
    id: objective
    attributes:
      label: Objectif
      description: Quelle documentation doit changer ?
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: À faire
      placeholder: |
        -
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes utiles
      placeholder: |
        - Fichier concerné :
        - Hors périmètre :
